<% project_name = 'keepr-api' %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: <%= keepr-api %>_development

test:
  <<: *default
  database: <%= keepr-api %>_test
